apiVersion: v1
kind: Service
metadata:
  name: meta-form-web
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 13000
  selector:
    app: meta-form-web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: meta-form-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meta-form-web
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: meta-form-web
    spec:
      containers:
      - name: meta-form-web
        image: 172.29.0.13:8082/meta-form-web:<BUILD_TAG>
        imagePullPolicy: Always
        volumeMounts:
        - name: time-zone
          mountPath: /etc/localtime
        - name: tomcat-logs
          mountPath: /usr/local/tomcat/logs
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: registry-secret
      volumes:
      - name: time-zone
        hostPath:
          path: /etc/localtime
      - name: tomcat-logs
        hostPath:
          path: /data/tomcat/logs